-- Estructura principal de datos de PendixAPP.

CREATE TABLE IF NOT EXISTS pendientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(160) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'activo',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_pendientes_estado
        CHECK (
            estado IN (
                'activo',
                'vencido',
                'completado'
            )
        )
);

CREATE INDEX IF NOT EXISTS idx_pendientes_estado
    ON pendientes (estado);
